const Recipes = [
  {
    id: 1,
    name: "Classic Margherita Pizza",
    imgUrl: "/images/Classic Margherita Pizza.webp",
    category: "Mains",
    price: 12.99,
    ingredients: [
      "Pizza Dough",
      "San Marzano Tomatoes",
      "Fresh Mozzarella",
      "Fresh Basil",
      "Extra Virgin Olive Oil",
      "Sea Salt",
    ],
  },
  {
    id: 2,
    name: "Avocado Toast",
    imgUrl: "/images/Avocado Toast.webp",
    category: "Breakfast",
    price: 7.99,
    ingredients: [
      "Sourdough Bread",
      "Ripe Avocado",
      "Lemon Juice",
      "Red Pepper Flakes",
      "Microgreens",
      "Sea Salt",
    ],
  },
  {
    id: 3,
    name: "Garlic Butter Steak",
    imgUrl: "/images/Garlic Butter Steak.webp",
    category: "Mains",
    price: 24.5,
    ingredients: [
      "Ribeye Steak",
      "Unsalted Butter",
      "Garlic Cloves",
      "Fresh Rosemary",
      "Kosher Salt",
      "Black Pepper",
    ],
  },
  {
    id: 4,
    name: "Spaghetti Carbonara",
    imgUrl: "/images/Spaghetti Carbonara.webp",
    category: "Mains",
    price: 14.5,
    ingredients: [
      "Spaghetti",
      "Pancetta",
      "Egg Yolks",
      "Pecorino Romano",
      "Black Pepper",
    ],
  },
  {
    id: 5,
    name: "Chicken Caesar Salad",
    imgUrl: "/images/Chicken Caesar Salad.webp",
    category: "Appetizers",
    price: 11.25,
    ingredients: [
      "Chicken Breast",
      "Romaine Lettuce",
      "Croutons",
      "Parmesan Cheese",
      "Caesar Dressing",
    ],
  },
  {
    id: 6,
    name: "Matcha Green Tea Latte",
    imgUrl: "/images/Matcha Green Tea Latte.webp",
    category: "Drinks",
    price: 4.75,
    ingredients: ["Matcha Powder", "Hot Water", "Oat Milk", "Honey"],
  },
  {
    id: 7,
    name: "Beef Tacos",
    imgUrl: "/images/Beef Tacos.webp",
    category: "Mains",
    price: 10.99,
    ingredients: [
      "Ground Beef",
      "Taco Shells",
      "Shredded Lettuce",
      "Cheddar Cheese",
      "Salsa",
    ],
  },
  {
    id: 8,
    name: "French Onion Soup",
    imgUrl: "/images/French Onion Soup.webp",
    category: "Appetizers",
    price: 8.5,
    ingredients: [
      "Yellow Onions",
      "Beef Broth",
      "Gruyere Cheese",
      "Baguette",
      "Butter",
    ],
  },
  {
    id: 9,
    name: "Classic Pancakes",
    imgUrl: "/images/Classic Pancakes.webp",
    category: "Breakfast",
    price: 9.25,
    ingredients: ["Flour", "Milk", "Eggs", "Baking Powder", "Maple Syrup"],
  },
  {
    id: 10,
    name: "Sushi California Roll",
    imgUrl: "/images/Sushi California Roll.webp",
    category: "Appetizers",
    price: 9.99,
    ingredients: [
      "Sushi Rice",
      "Nori Sheets",
      "Imitation Crab",
      "Avocado",
      "Cucumber",
    ],
  },
  {
    id: 11,
    name: "Shrimp Scampi",
    imgUrl: "/images/Shrimp Scampi.webp",
    category: "Mains",
    price: 18.75,
    ingredients: [
      "Shrimp",
      "Linguine",
      "Garlic",
      "White Wine",
      "Lemon Juice",
      "Butter",
    ],
  },
  {
    id: 12,
    name: "Greek Salad",
    imgUrl: "/images/Greek Salad.webp",
    category: "Appetizers",
    price: 10.5,
    ingredients: [
      "Cucumbers",
      "Tomatoes",
      "Feta Cheese",
      "Kalamata Olives",
      "Olive Oil",
    ],
  },
  {
    id: 13,
    name: "Chocolate Brownies",
    imgUrl: "/images/Chocolate Brownies.webp",
    category: "Desserts",
    price: 5.5,
    ingredients: [
      "Cocoa Powder",
      "Sugar",
      "Flour",
      "Butter",
      "Eggs",
      "Chocolate Chips",
    ],
  },
  {
    id: 14,
    name: "Vegetable Stir Fry",
    imgUrl: "/images/Vegetable Stir Fry.webp",
    category: "Mains",
    price: 13.25,
    ingredients: [
      "Broccoli",
      "Bell Peppers",
      "Carrots",
      "Soy Sauce",
      "Sesame Oil",
      "Tofu",
    ],
  },
  {
    id: 15,
    name: "BBQ Pulled Pork Sandwich",
    imgUrl: "/images/BBQ Pulled Pork Sandwich.webp",
    category: "Mains",
    price: 13.99,
    ingredients: ["Pork Shoulder", "BBQ Sauce", "Brioche Buns", "Coleslaw"],
  },
  {
    id: 16,
    name: "Chicken Tikka Masala",
    imgUrl: "/images/Chicken Tikka Masala.webp",
    category: "Mains",
    price: 16.5,
    ingredients: [
      "Chicken",
      "Yogurt",
      "Garam Masala",
      "Heavy Cream",
      "Tomato Puree",
    ],
  },
  {
    id: 17,
    name: "Eggs Benedict",
    imgUrl: "/images/Eggs Benedict.webp",
    category: "Breakfast",
    price: 12.5,
    ingredients: [
      "Poached Eggs",
      "English Muffin",
      "Canadian Bacon",
      "Hollandaise Sauce",
    ],
  },
  {
    id: 18,
    name: "Classic Beef Burger",
    imgUrl: "/images/Classic Beef Burger.webp",
    category: "Mains",
    price: 12.5,
    ingredients: [
      "Beef Patty",
      "Burger Bun",
      "Cheddar Cheese",
      "Lettuce",
      "Tomato",
      "Pickles",
    ],
  },
  {
    id: 19,
    name: "Tom Yum Soup",
    imgUrl: "/images/Tom Yum Soup.webp",
    category: "Appetizers",
    price: 8.99,
    ingredients: [
      "Shrimp",
      "Lemongrass",
      "Galangal",
      "Kaffir Lime Leaves",
      "Chili Paste",
      "Mushrooms",
    ],
  },
  {
    id: 20,
    name: "Acai Bowl",
    imgUrl: "/images/Acai Bowl.webp",
    category: "Breakfast",
    price: 9.99,
    ingredients: [
      "Acai Puree",
      "Banana",
      "Granola",
      "Strawberries",
      "Chia Seeds",
      "Almond Milk",
    ],
  },
];

export default Recipes;
